language: android

node_js:
  - 5.5

notifications:
  email: false

sudo: false

branches:
  only:
  - main

before_script:
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  
