language: node_js

node_js:
  - 7

cache:
  npm: false
  
branches:
  only:
  - main 
  
install:
  - npm cache clean
  - npm install
  - npm install -g cordova

before_script:
  - cordova platform add android --nofetch

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  
