language: node_js

node_js:
  - 7

cache:
  npm: false
  
branches:
  only:
  - main
  
before_install:
  - npm i -g npm  

install:
  - npm cache clean
  - npm install
  - npm install -g cordova

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  
